logging:
  config: classpath:logback.xml
  path: d:/logs
server:
  servlet:
    session:
      timeout: 1800
  port: 8080

spring:
    redis:
       database: 0
       host: 192.168.253.128
       port: 6379
       password: 1234
       timeout: 10000              #客户端超时时间单位是毫秒 默认是2000
       jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    session:
      store-type: none